config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'roles#index'
  resources :users
  resources :roles
  resources :items
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Item if user.role.permissions[:read]=="1" ? true : false
    can :create, Item if user.role.permissions[:write]=="1" ? true : false
    can :edit, Item if user.role.permissions[:write]=="1" ? true : false
    can :destroy, Item if user.role.permissions[:destroy]=="1" ? true : false
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  # belongs_to :user
  has_one :user
  validates :name, presence: true

  serialize :permissions, Hash
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :role
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do
    flash[:error] = 'Access denied!'
    redirect_to root_url
  end

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password,:role_id)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :role_id)}
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  load_and_authorize_resource

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    item = current_user.items.new(item_params)
    if item.save
      redirect_to notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      redirect_to @item, notice: 'Item was successfully updated.'
    else
       :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  def index
    @roles = Role.all
  end

  def new
    @role = Role.new
  end

  def show
    @role = Role.find(params[:id])
  end

  def edit
    @role = Role.find(params[:id])
  end

  def create
    role = Role.new(name: role_params[:name], permissions: {read: role_params[:read], write: role_params[:write], destroy: role_params[:destroy]})
    if role.save
      redirect_to notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  def update
    @role = Role.find(params[:id])
    @role.update(name: role_params[:name], permissions: {read: role_params[:read], write: role_params[:write], destroy: role_params[:destroy]})
    if @role.save
      redirect_to @role, notice: 'Role was successfully updated.'
    else
       :edit
    end
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy
    redirect_to roles_url, notice: 'Role was successfully destroyed.'
  end

  private

  def role_params
    params.require(:role).permit(:name, :read, :write, :destroy)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to @user, notice: 'Role was successfully updated.'
    else
       :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to roles_url, notice: 'Role was successfully destroyed.'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Action's</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <% if can? :read, item %>
          <td><%= link_to 'Show', item %></td>
        <% end %>

        <% if can? :create, item %>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <% end %>

        <% if can? :destroy, item %>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Role</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p> <strong>Name:</strong> <%= @item.name %> </p>

<% if can? :create, @item %>
  <%= link_to 'Edit', edit_item_path(@item) %> |
<% end %>
<%= link_to 'Back',  items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if user_signed_in? %>
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Edit profile", edit_user_registration_path %>
      <%= link_to "Users", users_path %>
      <%= link_to "Items", items_path %>
      <%= link_to "Roles", roles_path %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or
      <%= link_to "sign in", new_user_session_path %>
    <% end %>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/roles/_form.html.erb
<%= form_with(model: role) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <h5>Role-Permissions</h5>
  <div class="field">
    <%= f.label :read %>
    <%= f.check_box :read, checked:  @role.permissions[:read] =="1" ? true : false %>
  </div>

  <div class="field">
    <%= f.label :write %>
    <%= f.check_box :write, checked:  @role.permissions[:write] =="1" ? true : false %>
  </div>

  <div class="field">
    <%= f.label :destroy %>
    <%= f.check_box :destroy, checked:  @role.permissions[:destroy] =="1" ? true : false %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p> <strong>Name:</strong> <%= @role.name %> </p>

<b>Permissions</b>
<p> Read: <%= @role.permissions[:read]=="1" ? true : false %> </p>

<p> Write: <%= @role.permissions[:write]=="1" ? true : false  %> </p>

<p> Destroy: <%= @role.permissions[:destroy]=="1" ? true : false  %> </p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :role_id %>
    <%= collection_select(:user, :role_id, Role.all, :id, :name, { prompt: true }) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users-List</h1>

<table>
  <thead>
    <tr>
      <th>User-Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User',  new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>